// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: soa_invoke.proto

package proto3

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SoaInvokerRequest struct {
	ReqId                string   `protobuf:"bytes,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	RpcId                string   `protobuf:"bytes,2,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
	Iface                string   `protobuf:"bytes,3,opt,name=iface,proto3" json:"iface,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	RequestJson          string   `protobuf:"bytes,5,opt,name=requestJson,proto3" json:"requestJson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoaInvokerRequest) Reset()         { *m = SoaInvokerRequest{} }
func (m *SoaInvokerRequest) String() string { return proto.CompactTextString(m) }
func (*SoaInvokerRequest) ProtoMessage()    {}
func (*SoaInvokerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee554f9b31f76e6c, []int{0}
}
func (m *SoaInvokerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SoaInvokerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SoaInvokerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SoaInvokerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoaInvokerRequest.Merge(m, src)
}
func (m *SoaInvokerRequest) XXX_Size() int {
	return m.Size()
}
func (m *SoaInvokerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SoaInvokerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SoaInvokerRequest proto.InternalMessageInfo

func (m *SoaInvokerRequest) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *SoaInvokerRequest) GetRpcId() string {
	if m != nil {
		return m.RpcId
	}
	return ""
}

func (m *SoaInvokerRequest) GetIface() string {
	if m != nil {
		return m.Iface
	}
	return ""
}

func (m *SoaInvokerRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SoaInvokerRequest) GetRequestJson() string {
	if m != nil {
		return m.RequestJson
	}
	return ""
}

type SoaInvokerResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ResultJson           string   `protobuf:"bytes,3,opt,name=resultJson,proto3" json:"resultJson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoaInvokerResponse) Reset()         { *m = SoaInvokerResponse{} }
func (m *SoaInvokerResponse) String() string { return proto.CompactTextString(m) }
func (*SoaInvokerResponse) ProtoMessage()    {}
func (*SoaInvokerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee554f9b31f76e6c, []int{1}
}
func (m *SoaInvokerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SoaInvokerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SoaInvokerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SoaInvokerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoaInvokerResponse.Merge(m, src)
}
func (m *SoaInvokerResponse) XXX_Size() int {
	return m.Size()
}
func (m *SoaInvokerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SoaInvokerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SoaInvokerResponse proto.InternalMessageInfo

func (m *SoaInvokerResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SoaInvokerResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SoaInvokerResponse) GetResultJson() string {
	if m != nil {
		return m.ResultJson
	}
	return ""
}

type SoaHealthCheckRequest struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoaHealthCheckRequest) Reset()         { *m = SoaHealthCheckRequest{} }
func (m *SoaHealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*SoaHealthCheckRequest) ProtoMessage()    {}
func (*SoaHealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee554f9b31f76e6c, []int{2}
}
func (m *SoaHealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SoaHealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SoaHealthCheckRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SoaHealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoaHealthCheckRequest.Merge(m, src)
}
func (m *SoaHealthCheckRequest) XXX_Size() int {
	return m.Size()
}
func (m *SoaHealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SoaHealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SoaHealthCheckRequest proto.InternalMessageInfo

func (m *SoaHealthCheckRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type SoaHealthCheckResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoaHealthCheckResponse) Reset()         { *m = SoaHealthCheckResponse{} }
func (m *SoaHealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*SoaHealthCheckResponse) ProtoMessage()    {}
func (*SoaHealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee554f9b31f76e6c, []int{3}
}
func (m *SoaHealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SoaHealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SoaHealthCheckResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SoaHealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoaHealthCheckResponse.Merge(m, src)
}
func (m *SoaHealthCheckResponse) XXX_Size() int {
	return m.Size()
}
func (m *SoaHealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SoaHealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SoaHealthCheckResponse proto.InternalMessageInfo

func (m *SoaHealthCheckResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*SoaInvokerRequest)(nil), "proto3.SoaInvokerRequest")
	proto.RegisterType((*SoaInvokerResponse)(nil), "proto3.SoaInvokerResponse")
	proto.RegisterType((*SoaHealthCheckRequest)(nil), "proto3.SoaHealthCheckRequest")
	proto.RegisterType((*SoaHealthCheckResponse)(nil), "proto3.SoaHealthCheckResponse")
}

func init() { proto.RegisterFile("soa_invoke.proto", fileDescriptor_ee554f9b31f76e6c) }

var fileDescriptor_ee554f9b31f76e6c = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0xd9, 0x3f, 0xa5, 0xc9, 0x7f, 0xbc, 0xe0, 0x44, 0x49, 0x25, 0x71, 0x43, 0x7a, 0x22,
	0x31, 0x21, 0x44, 0x1e, 0xc0, 0x44, 0x63, 0x14, 0x8f, 0x70, 0xf3, 0x62, 0xd6, 0xed, 0x00, 0x0d,
	0xa5, 0x5b, 0x76, 0x0b, 0xaf, 0xe1, 0xd5, 0x47, 0xf2, 0xe8, 0x23, 0x18, 0xf4, 0x41, 0x0c, 0xbb,
	0xab, 0xa9, 0xa2, 0x17, 0x4f, 0x9d, 0xef, 0xf7, 0x4d, 0x66, 0xbf, 0x99, 0x14, 0x9a, 0x46, 0x89,
	0xbb, 0x34, 0x5f, 0xab, 0x39, 0xf5, 0x0a, 0xad, 0x4a, 0x85, 0xa1, 0xfd, 0x0c, 0xe2, 0x07, 0x06,
	0xfb, 0x63, 0x25, 0x86, 0xd6, 0xd3, 0x23, 0x5a, 0xae, 0xc8, 0x94, 0x78, 0x00, 0x0d, 0x4d, 0xcb,
	0x61, 0x12, 0xb1, 0x0e, 0xeb, 0xfe, 0x1f, 0x39, 0x61, 0x69, 0x21, 0x87, 0x49, 0xf4, 0xcf, 0xd3,
	0xad, 0xd8, 0xd2, 0x74, 0x22, 0x24, 0x45, 0x75, 0x47, 0xad, 0xc0, 0x16, 0x84, 0x0b, 0x2a, 0x67,
	0x2a, 0x89, 0x02, 0x8b, 0xbd, 0xc2, 0x0e, 0xec, 0x69, 0xf7, 0xc8, 0x8d, 0x51, 0x79, 0xd4, 0xb0,
	0x66, 0x15, 0xc5, 0xb7, 0x80, 0xd5, 0x40, 0xa6, 0x50, 0xb9, 0x21, 0x44, 0x08, 0xa4, 0x4a, 0xc8,
	0x06, 0x6a, 0x8c, 0x6c, 0x8d, 0x4d, 0xa8, 0x2f, 0xcc, 0xd4, 0xa7, 0xd9, 0x96, 0xc8, 0x01, 0x34,
	0x99, 0x55, 0xe6, 0x86, 0xbb, 0x40, 0x15, 0x12, 0x9f, 0xc0, 0xe1, 0x58, 0x89, 0x6b, 0x12, 0x59,
	0x39, 0xbb, 0x98, 0x91, 0x9c, 0x7f, 0x2c, 0x8c, 0x10, 0xa4, 0xf9, 0x44, 0xf9, 0x7d, 0x6d, 0x1d,
	0xf7, 0xa1, 0xf5, 0xbd, 0xd9, 0x87, 0x69, 0x41, 0xe8, 0x86, 0xfa, 0x7e, 0xaf, 0x4e, 0xdf, 0xbe,
	0x1c, 0x73, 0x4c, 0x7a, 0x9d, 0x4a, 0xc2, 0x33, 0x08, 0xa4, 0xc8, 0x32, 0x3c, 0x72, 0xa7, 0x1f,
	0xf4, 0x76, 0xee, 0xdd, 0x6e, 0xff, 0x64, 0xb9, 0xc7, 0xe2, 0x1a, 0x5e, 0x41, 0x50, 0xa4, 0xf9,
	0x14, 0x8f, 0x2b, 0x5d, 0xbb, 0x3b, 0xb4, 0xf9, 0x6f, 0xf6, 0xe7, 0xa0, 0x4b, 0x08, 0x4d, 0xa9,
	0x49, 0x2c, 0xfe, 0x9c, 0xa5, 0xcb, 0xfa, 0xec, 0xbc, 0xf9, 0xb4, 0xe1, 0xec, 0x79, 0xc3, 0xd9,
	0xcb, 0x86, 0xb3, 0xc7, 0x57, 0x5e, 0xbb, 0xf7, 0x7f, 0xd3, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x94, 0x71, 0x05, 0xb9, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SoaInvokerServiceClient is the client API for SoaInvokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SoaInvokerServiceClient interface {
	Call(ctx context.Context, in *SoaInvokerRequest, opts ...grpc.CallOption) (*SoaInvokerResponse, error)
	Ping(ctx context.Context, in *SoaHealthCheckRequest, opts ...grpc.CallOption) (*SoaHealthCheckResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (SoaInvokerService_StreamClient, error)
}

type soaInvokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSoaInvokerServiceClient(cc *grpc.ClientConn) SoaInvokerServiceClient {
	return &soaInvokerServiceClient{cc}
}

func (c *soaInvokerServiceClient) Call(ctx context.Context, in *SoaInvokerRequest, opts ...grpc.CallOption) (*SoaInvokerResponse, error) {
	out := new(SoaInvokerResponse)
	err := c.cc.Invoke(ctx, "/proto3.SoaInvokerService/call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soaInvokerServiceClient) Ping(ctx context.Context, in *SoaHealthCheckRequest, opts ...grpc.CallOption) (*SoaHealthCheckResponse, error) {
	out := new(SoaHealthCheckResponse)
	err := c.cc.Invoke(ctx, "/proto3.SoaInvokerService/ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *soaInvokerServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (SoaInvokerService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SoaInvokerService_serviceDesc.Streams[0], "/proto3.SoaInvokerService/stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &soaInvokerServiceStreamClient{stream}
	return x, nil
}

type SoaInvokerService_StreamClient interface {
	Send(*SoaInvokerRequest) error
	Recv() (*SoaInvokerResponse, error)
	grpc.ClientStream
}

type soaInvokerServiceStreamClient struct {
	grpc.ClientStream
}

func (x *soaInvokerServiceStreamClient) Send(m *SoaInvokerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *soaInvokerServiceStreamClient) Recv() (*SoaInvokerResponse, error) {
	m := new(SoaInvokerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SoaInvokerServiceServer is the server API for SoaInvokerService service.
type SoaInvokerServiceServer interface {
	Call(context.Context, *SoaInvokerRequest) (*SoaInvokerResponse, error)
	Ping(context.Context, *SoaHealthCheckRequest) (*SoaHealthCheckResponse, error)
	Stream(SoaInvokerService_StreamServer) error
}

// UnimplementedSoaInvokerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSoaInvokerServiceServer struct {
}

func (*UnimplementedSoaInvokerServiceServer) Call(ctx context.Context, req *SoaInvokerRequest) (*SoaInvokerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedSoaInvokerServiceServer) Ping(ctx context.Context, req *SoaHealthCheckRequest) (*SoaHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedSoaInvokerServiceServer) Stream(srv SoaInvokerService_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterSoaInvokerServiceServer(s *grpc.Server, srv SoaInvokerServiceServer) {
	s.RegisterService(&_SoaInvokerService_serviceDesc, srv)
}

func _SoaInvokerService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoaInvokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoaInvokerServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto3.SoaInvokerService/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoaInvokerServiceServer).Call(ctx, req.(*SoaInvokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SoaInvokerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoaHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoaInvokerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto3.SoaInvokerService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoaInvokerServiceServer).Ping(ctx, req.(*SoaHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SoaInvokerService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SoaInvokerServiceServer).Stream(&soaInvokerServiceStreamServer{stream})
}

type SoaInvokerService_StreamServer interface {
	Send(*SoaInvokerResponse) error
	Recv() (*SoaInvokerRequest, error)
	grpc.ServerStream
}

type soaInvokerServiceStreamServer struct {
	grpc.ServerStream
}

func (x *soaInvokerServiceStreamServer) Send(m *SoaInvokerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *soaInvokerServiceStreamServer) Recv() (*SoaInvokerRequest, error) {
	m := new(SoaInvokerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SoaInvokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto3.SoaInvokerService",
	HandlerType: (*SoaInvokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "call",
			Handler:    _SoaInvokerService_Call_Handler,
		},
		{
			MethodName: "ping",
			Handler:    _SoaInvokerService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "stream",
			Handler:       _SoaInvokerService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "soa_invoke.proto",
}

func (m *SoaInvokerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SoaInvokerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SoaInvokerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.RequestJson) > 0 {
		i -= len(m.RequestJson)
		copy(dAtA[i:], m.RequestJson)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.RequestJson)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Iface) > 0 {
		i -= len(m.Iface)
		copy(dAtA[i:], m.Iface)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.Iface)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RpcId) > 0 {
		i -= len(m.RpcId)
		copy(dAtA[i:], m.RpcId)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.RpcId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ReqId) > 0 {
		i -= len(m.ReqId)
		copy(dAtA[i:], m.ReqId)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.ReqId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SoaInvokerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SoaInvokerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SoaInvokerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ResultJson) > 0 {
		i -= len(m.ResultJson)
		copy(dAtA[i:], m.ResultJson)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.ResultJson)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x12
	}
	if m.Code != 0 {
		i = encodeVarintSoaInvoke(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SoaHealthCheckRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SoaHealthCheckRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SoaHealthCheckRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SoaHealthCheckResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SoaHealthCheckResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SoaHealthCheckResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintSoaInvoke(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSoaInvoke(dAtA []byte, offset int, v uint64) int {
	offset -= sovSoaInvoke(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SoaInvokerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReqId)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	l = len(m.RpcId)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	l = len(m.Iface)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	l = len(m.RequestJson)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SoaInvokerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovSoaInvoke(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	l = len(m.ResultJson)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SoaHealthCheckRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SoaHealthCheckResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovSoaInvoke(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSoaInvoke(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSoaInvoke(x uint64) (n int) {
	return sovSoaInvoke(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SoaInvokerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSoaInvoke
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SoaInvokerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SoaInvokerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpcId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpcId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Iface", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Iface = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestJson = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSoaInvoke(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SoaInvokerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSoaInvoke
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SoaInvokerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SoaInvokerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultJson = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSoaInvoke(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SoaHealthCheckRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSoaInvoke
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SoaHealthCheckRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SoaHealthCheckRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSoaInvoke(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SoaHealthCheckResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSoaInvoke
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SoaHealthCheckResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SoaHealthCheckResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSoaInvoke(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSoaInvoke
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSoaInvoke(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSoaInvoke
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSoaInvoke
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSoaInvoke
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSoaInvoke
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSoaInvoke
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSoaInvoke        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSoaInvoke          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSoaInvoke = fmt.Errorf("proto: unexpected end of group")
)
