// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: soa_invoke.proto

package proto2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoaInvokerRequest struct {


	ReqId       string `protobuf:"bytes,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	RpcId       string `protobuf:"bytes,2,opt,name=rpcId,proto3" json:"rpcId,omitempty"`
	Iface       string `protobuf:"bytes,3,opt,name=iface,proto3" json:"iface,omitempty"`
	Method      string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	RequestJson string `protobuf:"bytes,5,opt,name=requestJson,proto3" json:"requestJson,omitempty"`
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SoaInvokerRequest) Reset() {
	*x = SoaInvokerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soa_invoke_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoaInvokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoaInvokerRequest) ProtoMessage() {}

func (x *SoaInvokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soa_invoke_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoaInvokerRequest.ProtoReflect.Descriptor instead.
func (*SoaInvokerRequest) Descriptor() ([]byte, []int) {
	return file_soa_invoke_proto_rawDescGZIP(), []int{0}
}

func (x *SoaInvokerRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *SoaInvokerRequest) GetRpcId() string {
	if x != nil {
		return x.RpcId
	}
	return ""
}

func (x *SoaInvokerRequest) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *SoaInvokerRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SoaInvokerRequest) GetRequestJson() string {
	if x != nil {
		return x.RequestJson
	}
	return ""
}

type SoaInvokerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg        string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ResultJson string `protobuf:"bytes,3,opt,name=resultJson,proto3" json:"resultJson,omitempty"`
}

func (x *SoaInvokerResponse) Reset() {
	*x = SoaInvokerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soa_invoke_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoaInvokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoaInvokerResponse) ProtoMessage() {}

func (x *SoaInvokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soa_invoke_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoaInvokerResponse.ProtoReflect.Descriptor instead.
func (*SoaInvokerResponse) Descriptor() ([]byte, []int) {
	return file_soa_invoke_proto_rawDescGZIP(), []int{1}
}

func (x *SoaInvokerResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SoaInvokerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SoaInvokerResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type SoaHealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SoaHealthCheckRequest) Reset() {
	*x = SoaHealthCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soa_invoke_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoaHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoaHealthCheckRequest) ProtoMessage() {}

func (x *SoaHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soa_invoke_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoaHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*SoaHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_soa_invoke_proto_rawDescGZIP(), []int{2}
}

func (x *SoaHealthCheckRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type SoaHealthCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SoaHealthCheckResponse) Reset() {
	*x = SoaHealthCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soa_invoke_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoaHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoaHealthCheckResponse) ProtoMessage() {}

func (x *SoaHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soa_invoke_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoaHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*SoaHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_soa_invoke_proto_rawDescGZIP(), []int{3}
}

func (x *SoaHealthCheckResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_soa_invoke_proto protoreflect.FileDescriptor

var file_soa_invoke_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x6f, 0x61, 0x5f, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x22, 0x8f, 0x01, 0x0a, 0x11, 0x53,
	0x6f, 0x61, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x70, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x66, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x12,
	0x53, 0x6f, 0x61, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x15, 0x53, 0x6f, 0x61, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x30, 0x0a, 0x16, 0x53, 0x6f, 0x61, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xe4, 0x01, 0x0a, 0x11, 0x53, 0x6f, 0x61, 0x49,
	0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a,
	0x04, 0x63, 0x61, 0x6c, 0x6c, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x2e, 0x53,
	0x6f, 0x61, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x2e, 0x53, 0x6f, 0x61, 0x49, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47,
	0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x2e,
	0x53, 0x6f, 0x61, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x2e, 0x53,
	0x6f, 0x61, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x2e, 0x53, 0x6f, 0x61, 0x49, 0x6e,
	0x76, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x32, 0x2e, 0x53, 0x6f, 0x61, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_soa_invoke_proto_rawDescOnce sync.Once
	file_soa_invoke_proto_rawDescData = file_soa_invoke_proto_rawDesc
)

func file_soa_invoke_proto_rawDescGZIP() []byte {
	file_soa_invoke_proto_rawDescOnce.Do(func() {
		file_soa_invoke_proto_rawDescData = protoimpl.X.CompressGZIP(file_soa_invoke_proto_rawDescData)
	})
	return file_soa_invoke_proto_rawDescData
}

var file_soa_invoke_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_soa_invoke_proto_goTypes = []interface{}{
	(*SoaInvokerRequest)(nil),      // 0: proto2.SoaInvokerRequest
	(*SoaInvokerResponse)(nil),     // 1: proto2.SoaInvokerResponse
	(*SoaHealthCheckRequest)(nil),  // 2: proto2.SoaHealthCheckRequest
	(*SoaHealthCheckResponse)(nil), // 3: proto2.SoaHealthCheckResponse
}
var file_soa_invoke_proto_depIdxs = []int32{
	0, // 0: proto2.SoaInvokerService.call:input_type -> proto2.SoaInvokerRequest
	2, // 1: proto2.SoaInvokerService.ping:input_type -> proto2.SoaHealthCheckRequest
	0, // 2: proto2.SoaInvokerService.stream:input_type -> proto2.SoaInvokerRequest
	1, // 3: proto2.SoaInvokerService.call:output_type -> proto2.SoaInvokerResponse
	3, // 4: proto2.SoaInvokerService.ping:output_type -> proto2.SoaHealthCheckResponse
	1, // 5: proto2.SoaInvokerService.stream:output_type -> proto2.SoaInvokerResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_soa_invoke_proto_init() }
func file_soa_invoke_proto_init() {
	if File_soa_invoke_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_soa_invoke_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoaInvokerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soa_invoke_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoaInvokerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soa_invoke_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoaHealthCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soa_invoke_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoaHealthCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_soa_invoke_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_soa_invoke_proto_goTypes,
		DependencyIndexes: file_soa_invoke_proto_depIdxs,
		MessageInfos:      file_soa_invoke_proto_msgTypes,
	}.Build()
	File_soa_invoke_proto = out.File
	file_soa_invoke_proto_rawDesc = nil
	file_soa_invoke_proto_goTypes = nil
	file_soa_invoke_proto_depIdxs = nil
}
